#!/bin/bash

# TODO pass build args to docker containers via ENV Variables or something
# TODO set this up so we can provision individual pieces of the docker environment

# Setup App Backend
echo "Setting Up Docker Network 10.10.0.0"
echo "-----------------------------------"

# setup private network
docker network create --subnet=10.10.0.0/16 dockernet

# Setup API Gateway
echo "Building api-gateway-service container..."
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    docker build -t michaelharrisonroth/api-gateway-service /var/www/backend/api-gateway-service
    docker run --net dockernet --ip 10.10.0.2 --name api-gateway-service -v /var/www/backend/api-gateway-service/src:/usr/src/app -d michaelharrisonroth/api-gateway-service

else
    docker build -t michaelharrisonroth/api-gateway-service $(PWD)/../backend/api-gateway-service
    docker run --net dockernet --ip 10.10.0.2 --name api-gateway-service -v $(PWD)/../backend/api-gateway-service/src:/usr/src/app -d michaelharrisonroth/api-gateway-service
fi

# Setup Mongo DB
# TODO save db data to host
echo "Running mongodb container..."
docker run --net dockernet --ip 10.10.0.3 --name mongodb-master -d mongo

# Setup User Service
# TODO change this to auth service
echo "Building user-service..."
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    docker build -t michaelharrisonroth/user-service /var/www/backend/user-service
    docker run --net dockernet --ip 10.10.0.4 --name user-service -v /var/www/backend/user-service/src:/usr/src/app -d michaelharrisonroth/user-service
else
    docker build -t michaelharrisonroth/user-service $(PWD)/../backend/user-service
    docker run --net dockernet --ip 10.10.0.4 --name user-service -v $(PWD)/../backend/user-service/src:/usr/src/app -d michaelharrisonroth/user-service 
fi

Setup Generic Mongo REST Service
echo "Building mongo-rest-service..."
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    docker build -t michaelharrisonroth/mongo-rest-service /var/www/backend/mongo-rest-service
    docker run --net dockernet --ip 10.10.0.5 --name mongo-rest-service -v /var/www/backend/mongo-rest-service/src:/usr/src/app -d michaelharrisonroth/mongo-rest-service
else
    docker build -t michaelharrisonroth/mongo-rest-service $(PWD)/../backend/mongo-rest-service
    docker run --net dockernet --ip 10.10.0.5 --name mongo-rest-service -v $(PWD)/../backend/mongo-rest-service/src:/usr/src/app -d michaelharrisonroth/mongo-rest-service 
fi

# Setup Mysql DB
echo "Running mysql container..."
docker run --net dockernet --ip 10.10.0.6 --name mysql-master -e MYSQL_ROOT_PASSWORD=root -d mysql

# Setup Generic Mysql Rest Service
# TODO change this to auth service
echo "Building mysql-rest-service..."
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    docker build -t michaelharrisonroth/mysql-rest-service /var/www/backend/mysql-rest-service
    docker run --net dockernet --ip 10.10.0.7 --name mysql-rest-service -v /var/www/backend/mysql-rest-service/src:/var/www/html -d michaelharrisonroth/mysql-rest-service
else
    docker build -t michaelharrisonroth/mysql-rest-service $(PWD)/../backend/mysql-rest-service
    docker run --net dockernet --ip 10.10.0.7 --name mysql-rest-service -v $(PWD)/../backend/mysql-rest-service/src:/var/www/html -d michaelharrisonroth/mysql-rest-service 
fi
